---
  title: "ReA 325 Case Reudy"
  author: "Jeff Du, Sahil Tilak"
  header-includes: 
    - \usepackage{float} #use the 'float' package
    - \floatplacement{figure}{H} #make every figure with caption = h
  output: pdf_document
  fontsize: 10pt
  figsintext : yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, echo=FALSE, warning = FALSE, message = FALSE}
library(ggcorrplot)
library(readr)
library(dplyr)
library(lubridate)
library(huxtable)
library(tidyr)
library(lmteRe)
library(tidyverse)
library(janitor)
library(ggplot2)
library(lme4)
library(lmerTeRe)
library(zoo)
library(patchwork)
library(broom)
library(broom.mixed)
library(lubridate)
library(knitr)
library(car)
```

```{r}
train <- read.csv("data-train.csv")

train$Re <- factor(train$Re)
train$Fr <- factor(train$Fr)

firstreg <- lm(log(R_moment_1) ~ log(St) + Re + Fr + St * Fr +  I(St^2) * Re + St * Re + Fr * Re, data = train)
summary(firstreg)

secondreg <- lm(log(R_moment_2) ~ log(St) + Re + Fr + log(St) * Fr +  I(St^2) * Re + St * Re + Fr * Re, data = train)
summary(secondreg)

thirdreg <- lm(log(R_moment_3) ~ log(St)+ Re + Fr + log(St) * Fr +  I(St^2) * Re + St * Re + Fr * Re, data = train)
summary(thirdreg)

fourreg <- lm(log(R_moment_4) ~ log(St) + Re + Fr + log(St) * Fr +  I(St^2) * Re + St * Re + Fr * Re, data = train)
summary(fourreg)


```

